<?php

namespace Pep\Judo\JapBundle\Repository;

/**
 * ContestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContestRepository extends \Doctrine\ORM\EntityRepository
{
}
